name = "skland-endfield-checkin-pages"
compatibility_date = "2026-03-30"
pages_build_output_dir = "./public"

[[kv_namespaces]]
binding = "SKLAND_STORAGE"
id = "945dd22ac4aa45c69065c44bb09e5411"
preview_id = "945dd22ac4aa45c69065c44bb09e5411"
